### ISSUE TITLE
Program Won't Open or Launch [Bug]

### ISSUE THREAD

**Issue by AlekSheff** [ProgenixLLC/product-uploader-beta#4]
**Describe the bug**
The application won't launch normally. After going to Settings > Privacy > and clicking "Open anyway: the program crashes:

"Alek's Uploader unexpectedly quit"
See logs

**Expected behavior**
The program should open and run normally for all users.

**Additional context**
I'm running MacOS 14.4 on M1 Max

[Aleks Uploader Crash Log.zip](https://github.com/ProgenixLLC/product-uploader-beta/files/15079540/Aleks.Uploader.Crash.Log.zip)

**Comment by bigmac1337** [comment]
@AlekSheff Can you try something for me:

1. Navigate to the Home directory on your Mac
2. Navigate to the hidden folder ".Aleks Uploader" (may need to enable hidden folders)
3. Open settings.json
4. Copy the value of your token and paste it somewhere safe
5. Delete the token value from the settings.json file leaving behind ```"Token": ""```
6. Try to launch the app
7. If successful, paste the token value in the box again.


Context:
In order to secure the users token better, we do some stuff to the token before we store it in that settings file. I believe the app is trying to reverse the normal changes to the token we make and its not recognizing it.

**Comment by AlekSheff** [comment]
Hey, Barrett,

I followed the steps and the uploader worked and launched just fine even after deleting the key from the settings.json

**Comment by bigmac1337** [comment]
Baked in a small bit of code to handle this in the next release.
