### ISSUE TITLE
Uploader Fails & Stops [Bug]

### ISSUE THREAD

**Issue by AlekSheff** [ProgenixLLC/product-uploader-beta#5]
**Describe the bug**
When uploading a set of sticker images, the uploader will successfully upload some of the images, and then fail on one of them, without skipping over the failed upload, and without clearing the successfully uploaded images from the queue.

**To Reproduce**
Standard Uploading triggers the bug.

**Expected behavior**
The uploader should do it's best to upload as many images as possible, skipping any that result in an issue, but proceed to upload the remaining images.

**Additional context**
The product is the SPOKE Kiss-Cut Sticker. The design PNG's are about 2048px square.
[Error Files.zip](https://github.com/ProgenixLLC/product-uploader-beta/files/15155402/Error.Files.zip)

**Comment by bigmac1337** [comment]
@AlekSheff While triaging this issue, I managed to somehow fail to unsuccessfully upload products using the collection of images found in the folder you provided.

While the important take away from this issue is that _the upload process needs to upload as many products as it can despite any failures_, im still curious how you got the upload to fail for the second image you uploaded as this is something we can also look into preventing.

**Comment by AlekSheff** [comment]
[Stickers.zip](https://github.com/ProgenixLLC/product-uploader-beta/files/15155617/Stickers.zip)


Here's a file with 10 stickers, I haven't been able to upload all 10 without it failing
